export const SET_SHOES = "SET_SHOES";
export const FETCH_SHOES_FAILED = "FETCH_SHOES_FAILED";

export const SELECT_SHOE = "SELECT_SHOE";

export const ADD_SHOE_TO_BASKET = "ADD_SHOE_TO_BASKET";
export const ADD_SHOE_TO_BASKET_INIT = "ADD_SHOE_TO_BASKET_INIT";
export const ADD_SHOE_TO_BASKET_START = "ADD_SHOE_TO_BASKET_START";
export const ADD_SHOE_TO_BASKET_SUCCESS = "ADD_SHOE_TO_BASKET_SUCCESS";
export const ADD_SHOE_TO_BASKET_FAIL = "ADD_SHOE_TO_BASKET_FAIL";

export const REMOVE_SHOE_FROM_BASKET = "REMOVE_SHOE_FROM_BASKET";
export const REMOVE_SHOE_FROM_BASKET_INIT = "REMOVE_SHOE_FROM_BASKET_INIT";
export const REMOVE_SHOE_FROM_BASKET_START = "REMOVE_SHOE_FROM_BASKET_START";
export const REMOVE_SHOE_FROM_BASKET_SUCCESS =
  "REMOVE_SHOE_FROM_BASKET_SUCCESS";
export const REMOVE_SHOE_FROM_BASKET_FAIL = "REMOVE_SHOE_FROM_BASKET_FAIL";

export const USER_SIGN_UP_INIT = "USER_SIGN_UP_INIT";
export const USER_SIGN_UP_START = "USER_SIGN_UP_START";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";

export const USER_UPDATE_DETAILS_INIT = "USER_UPDATE_DETAILS_INIT";
export const USER_UPDATE_DETAILS_START = "USER_UPDATE_DETAILS_START";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";

export const COMPLETE_ORDER = "COMPLETE_ORDER";
export const ORDER_INIT = "ORDER_INIT";
export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const USER_SIGN_IN = "USER_SIGN_IN";
